#!/usr/bin/env python3
"""Apply the MPH multi-ROM runtime-profile shim to the pinned ndsrecomp runner.

The upstream runner currently hard-codes Metroid Prime Hunters USA rev-0 RAM
addresses for Prime Controls and direct mouse aim. This project supports more
than one retail revision, so those host-side hooks must be selected by exact
ROM SHA-1 instead of by title/address assumptions.

The address values are generated from config/mph_rom_profiles.json. The
registry records melonPrimeDS's MelonPrimeGameRomAddrTable.h as the source of
truth for the MPH runtime addresses.

The source patch is intentionally small, idempotent, and fail-closed. If the
pinned ndsrecomp source changes enough that the expected preimages are absent,
this script stops instead of guessing a patch against unknown code.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


SHA1_RE = re.compile(r"^[0-9a-f]{40}$")
MAIN_RAM_MIN = 0x02000000
MAIN_RAM_MAX = 0x023FFFFF


def parse_address(value: object, *, profile: str, field: str) -> int:
    if not isinstance(value, str):
        raise SystemExit(f"{profile}.{field}: expected a hex string")
    try:
        address = int(value, 0)
    except ValueError as exc:
        raise SystemExit(f"{profile}.{field}: invalid address {value!r}") from exc
    if not MAIN_RAM_MIN <= address <= MAIN_RAM_MAX:
        raise SystemExit(
            f"{profile}.{field}: 0x{address:08X} is outside DS main RAM"
        )
    return address


def load_runtime_profiles(registry_path: Path) -> list[dict[str, object]]:
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    profiles = registry.get("profiles")
    if not isinstance(profiles, dict) or not profiles:
        raise SystemExit("ROM profile registry has no profiles")

    result: list[dict[str, object]] = []
    for key, profile in profiles.items():
        if not isinstance(profile, dict):
            continue
        runtime = profile.get("runtime")
        if runtime is None:
            continue
        if not isinstance(runtime, dict):
            raise SystemExit(f"{key}.runtime must be an object")
        sha1 = profile.get("sha1")
        if not isinstance(sha1, str) or not SHA1_RE.fullmatch(sha1):
            raise SystemExit(f"{key}.sha1 must be 40 lowercase hex digits")
        result.append(
            {
                "key": key,
                "sha1": sha1,
                "morph_state": parse_address(
                    runtime.get("morph_state"), profile=key, field="morph_state"
                ),
                "aim_x": parse_address(
                    runtime.get("aim_x"), profile=key, field="aim_x"
                ),
                "aim_y": parse_address(
                    runtime.get("aim_y"), profile=key, field="aim_y"
                ),
            }
        )

    if not result:
        raise SystemExit("ROM profile registry contains no MPH runtime profiles")
    return result


def generated_header(profiles: list[dict[str, object]]) -> str:
    rows = []
    for profile in profiles:
        rows.append(
            "    {\"%s\", 0x%08Xu, 0x%08Xu, 0x%08Xu},  // %s"
            % (
                profile["sha1"],
                profile["morph_state"],
                profile["aim_x"],
                profile["aim_y"],
                profile["key"],
            )
        )
    return """#pragma once

#include <array>
#include <cstdint>

// Generated by MetroidPrimeHuntersRecomp/tools/patch_ndsrecomp_mph_runtime.py.
// Do not edit in the ndsrecomp checkout; edit config/mph_rom_profiles.json.
struct NdsMphRuntimeProfile {
    const char* sha1;
    uint32_t morph_state;
    uint32_t aim_x;
    uint32_t aim_y;
};

inline constexpr std::array<NdsMphRuntimeProfile, %d> kNdsMphRuntimeProfiles{{
%s
}};
""" % (len(rows), "\n".join(rows))


def patch_once(path: Path, old: str, new: str, marker: str) -> None:
    text = path.read_text(encoding="utf-8")
    if marker in text:
        return
    if old not in text:
        raise SystemExit(
            f"Refusing to patch {path}: expected pinned ndsrecomp preimage "
            f"for marker {marker!r} was not found"
        )
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


def patch_runner(framework_root: Path, registry_path: Path) -> None:
    runner_src = framework_root / "runner" / "src"
    title_h = runner_src / "title_patches.h"
    title_cpp = runner_src / "title_patches.cpp"
    frontend_cpp = runner_src / "frontend.cpp"
    main_cpp = runner_src / "main.cpp"
    for path in (title_h, title_cpp, frontend_cpp, main_cpp):
        if not path.is_file():
            raise SystemExit(f"Pinned ndsrecomp runner file not found: {path}")

    profiles = load_runtime_profiles(registry_path)
    generated = runner_src / "mph_runtime_profiles.generated.h"
    generated.write_text(generated_header(profiles), encoding="utf-8")

    patch_once(
        title_h,
        "void nds_title_patches_set_mph_mouse_aim(bool enabled);\n"
        "bool nds_title_patches_apply_mph_mouse_delta(int32_t dx, int32_t dy);\n",
        "// MPH_MULTIROM_RUNTIME_PROFILE: exact-ROM runtime profile selection.\n"
        "bool nds_title_patches_select_mph_runtime_profile(const char* rom_sha1);\n"
        "bool nds_title_patches_mph_in_ball();\n"
        "void nds_title_patches_set_mph_mouse_aim(bool enabled);\n"
        "bool nds_title_patches_apply_mph_mouse_delta(int32_t dx, int32_t dy);\n",
        "MPH_MULTIROM_RUNTIME_PROFILE",
    )

    patch_once(
        title_cpp,
        '#include "title_patches.h"\n',
        '#include "title_patches.h"\n'
        '#include "mph_runtime_profiles.generated.h"  // MPH_MULTIROM_PROFILE_HEADER\n',
        "MPH_MULTIROM_PROFILE_HEADER",
    )
    patch_once(
        title_cpp,
        "// AMHE0's native touch-look routine consumes these signed, per-frame fields.\n"
        "// Feeding deltas here while holding the stylus at center preserves the game\n"
        "// path but removes the finite physical touchscreen edge.\n"
        "constexpr uint32_t kMphUs10AimX = 0x020DE526u;\n"
        "constexpr uint32_t kMphUs10AimY = 0x020DE52Eu;\n",
        "// MPH_MULTIROM_RUNTIME_PROFILE: selected only by exact cartridge SHA-1.\n"
        "const NdsMphRuntimeProfile* g_mph_runtime_profile = nullptr;\n",
        "selected only by exact cartridge SHA-1",
    )
    patch_once(
        title_cpp,
        "void nds_title_patches_set_mph_mouse_aim(bool enabled) {\n"
        "    g_mph_mouse_aim = enabled;\n"
        "}\n\n"
        "bool nds_title_patches_apply_mph_mouse_delta(int32_t dx, int32_t dy) {\n"
        "    if (!g_mph_mouse_aim || (dx == 0 && dy == 0)) return false;\n"
        "    if (dx != 0)\n"
        "        bus_write_u32_slow(kMphUs10AimX, static_cast<uint32_t>(dx));\n"
        "    if (dy != 0)\n"
        "        bus_write_u32_slow(kMphUs10AimY, static_cast<uint32_t>(dy));\n"
        "    return true;\n"
        "}\n",
        "bool nds_title_patches_select_mph_runtime_profile(const char* rom_sha1) {\n"
        "    g_mph_mouse_aim = false;\n"
        "    g_mph_runtime_profile = nullptr;\n"
        "    if (!rom_sha1) return false;\n"
        "    for (const NdsMphRuntimeProfile& profile : kNdsMphRuntimeProfiles) {\n"
        "        if (std::strcmp(profile.sha1, rom_sha1) == 0) {\n"
        "            g_mph_runtime_profile = &profile;\n"
        "            return true;\n"
        "        }\n"
        "    }\n"
        "    return false;\n"
        "}\n\n"
        "bool nds_title_patches_mph_in_ball() {\n"
        "    return g_mph_runtime_profile &&\n"
        "           bus_read_u8_slow(g_mph_runtime_profile->morph_state) == 0x02u;\n"
        "}\n\n"
        "void nds_title_patches_set_mph_mouse_aim(bool enabled) {\n"
        "    g_mph_mouse_aim = enabled && g_mph_runtime_profile;\n"
        "}\n\n"
        "bool nds_title_patches_apply_mph_mouse_delta(int32_t dx, int32_t dy) {\n"
        "    if (!g_mph_mouse_aim || !g_mph_runtime_profile ||\n"
        "        (dx == 0 && dy == 0)) return false;\n"
        "    if (dx != 0)\n"
        "        bus_write_u32_slow(g_mph_runtime_profile->aim_x,\n"
        "                           static_cast<uint32_t>(dx));\n"
        "    if (dy != 0)\n"
        "        bus_write_u32_slow(g_mph_runtime_profile->aim_y,\n"
        "                           static_cast<uint32_t>(dy));\n"
        "    return true;\n"
        "}\n",
        "nds_title_patches_select_mph_runtime_profile",
    )

    patch_once(
        frontend_cpp,
        "constexpr uint32_t kMphUs10MorphState = 0x020DA818u;\n",
        "// MPH_MULTIROM_RUNTIME_PROFILE: morph address is selected by ROM SHA-1.\n",
        "morph address is selected by ROM SHA-1",
    )
    patch_once(
        frontend_cpp,
        "                const bool in_ball =\n"
        "                    bus_read_u8_slow(kMphUs10MorphState) == 0x02u;\n",
        "                const bool in_ball = nds_title_patches_mph_in_ball();\n",
        "nds_title_patches_mph_in_ball()",
    )

    patch_once(
        main_cpp,
        "    mph_mouse_aim_policy =\n"
        "        rom_sha1 == \"90164d1ac127ee5f9815ea4ae7de798c7b5fc629\" &&\n"
        "        frontend_options.relative_mouse_touch;\n",
        "    // MPH_MULTIROM_RUNTIME_PROFILE: host hooks are enabled only when the\n"
        "    // exact ROM SHA-1 has a validated revision-specific address profile.\n"
        "    const bool mph_runtime_profile =\n"
        "        nds_title_patches_select_mph_runtime_profile(rom_sha1.c_str());\n"
        "    mph_mouse_aim_policy =\n"
        "        mph_runtime_profile && frontend_options.relative_mouse_touch;\n",
        "host hooks are enabled only when the",
    )

    print(
        f"Patched ndsrecomp MPH runtime profiles: "
        + ", ".join(str(profile["key"]) for profile in profiles)
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--framework-root", type=Path, required=True)
    parser.add_argument("--profiles", type=Path, required=True)
    args = parser.parse_args()
    patch_runner(args.framework_root.resolve(), args.profiles.resolve())


if __name__ == "__main__":
    main()
