#!/usr/bin/env python3
"""Verify AMHE0 and prepare ignored ndsrecomp main/overlay inputs."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

try:
    import ndspy.codeCompression as code_compression
    import ndspy.rom
except ImportError as exc:
    raise SystemExit(
        "ndspy 4.2.0 is required; install requirements.txt into .venv"
    ) from exc


EXPECTED_ROM_SHA1 = "90164d1ac127ee5f9815ea4ae7de798c7b5fc629"
EXPECTED_ROM_SIZE = 64 * 1024 * 1024
EXPECTED_GAME_CODE = b"AMHE"
EXPECTED_REVISION = 0


def sha1(data: bytes) -> str:
    return hashlib.sha1(data).hexdigest()


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def write_seed_config(
    path: Path,
    *,
    name: str,
    program_id: str,
    load_address: int,
    entry_pc: int,
    binary: bytes,
) -> None:
    path.write_text(
        "\n".join(
            [
                "# AUTO-GENERATED by tools/prepare_mph.py; do not commit.",
                "[program]",
                f"name = {toml_string(name)}",
                f"id = {toml_string(program_id)}",
                f"load_address = 0x{load_address:08x}",
                f"size = 0x{len(binary):08x}",
                f"entry_pc = 0x{entry_pc:08x}",
                "authoritative_entry_points = false",
                "",
                "[identity]",
                f"sha1 = {toml_string(sha1(binary))}",
                "",
                "[[entry_point]]",
                f"addr = 0x{entry_pc:08x}",
                'mode = "arm"',
                'name = "entry"',
                'kind = "rom_header"',
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    rom_bytes = args.rom.read_bytes()
    digest = sha1(rom_bytes)
    if len(rom_bytes) != EXPECTED_ROM_SIZE:
        raise SystemExit(
            f"ROM size mismatch: got {len(rom_bytes)}, expected {EXPECTED_ROM_SIZE}"
        )
    if digest != EXPECTED_ROM_SHA1:
        raise SystemExit(
            f"ROM SHA-1 mismatch: got {digest}, expected {EXPECTED_ROM_SHA1}"
        )
    if rom_bytes[0x0C:0x10] != EXPECTED_GAME_CODE:
        raise SystemExit(
            f"game code mismatch: got {rom_bytes[0x0C:0x10]!r}, "
            f"expected {EXPECTED_GAME_CODE!r}"
        )
    if rom_bytes[0x1C] != EXPECTED_REVISION:
        raise SystemExit(
            f"ROM revision mismatch: got {rom_bytes[0x1C]}, "
            f"expected {EXPECTED_REVISION}"
        )

    rom = ndspy.rom.NintendoDSRom(rom_bytes)
    arm9_compressed = bytes(rom.arm9)
    arm9 = code_compression.decompress(arm9_compressed)
    if len(arm9) < len(arm9_compressed):
        arm9 = arm9_compressed
    arm7 = bytes(rom.arm7)

    out = args.out.resolve()
    overlays_dir = out / "overlays"
    overlays_dir.mkdir(parents=True, exist_ok=True)
    (out / "arm9.bin").write_bytes(arm9)
    (out / "arm7.bin").write_bytes(arm7)

    write_seed_config(
        out / "arm9.toml",
        name="Metroid Prime Hunters (USA rev 0) ARM9 main",
        program_id="mph_amhe0_arm9",
        load_address=int(rom.arm9RamAddress),
        entry_pc=int(rom.arm9EntryAddress),
        binary=arm9,
    )
    write_seed_config(
        out / "arm7.toml",
        name="Metroid Prime Hunters (USA rev 0) ARM7",
        program_id="mph_amhe0_arm7",
        load_address=int(rom.arm7RamAddress),
        entry_pc=int(rom.arm7EntryAddress),
        binary=arm7,
    )

    overlay_manifest: list[dict[str, object]] = []
    for overlay_id, overlay in sorted(rom.loadArm9Overlays().items()):
        data = bytes(overlay.data)
        if len(data) != int(overlay.ramSize):
            raise SystemExit(
                f"overlay {overlay_id} length mismatch: "
                f"{len(data)} != {overlay.ramSize}"
            )
        filename = f"arm9_overlay_{overlay_id:03d}.bin"
        (overlays_dir / filename).write_bytes(data)
        overlay_manifest.append(
            {
                "id": overlay_id,
                "file": filename,
                "file_id": int(overlay.fileID),
                "load_address": f"0x{int(overlay.ramAddress):08x}",
                "size": int(overlay.ramSize),
                "bss_size": int(overlay.bssSize),
                "static_init_start": f"0x{int(overlay.staticInitStart):08x}",
                "static_init_end": f"0x{int(overlay.staticInitEnd):08x}",
                "compressed_in_rom": bool(overlay.compressed),
                "compressed_size": int(overlay.compressedSize),
                "sha1": sha1(data),
            }
        )
    (out / "overlays.json").write_text(
        json.dumps(overlay_manifest, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"ROM verified: AMHE revision 0, SHA-1 {digest}")
    print(
        f"ARM9: {len(arm9_compressed):,} compressed bytes -> "
        f"{len(arm9):,} bytes at 0x{int(rom.arm9RamAddress):08X}"
    )
    print(
        f"ARM7: {len(arm7):,} bytes at "
        f"0x{int(rom.arm7RamAddress):08X}"
    )
    print(f"ARM9 overlays: {len(overlay_manifest)} extracted and inventoried")
    print(f"Prepared ignored inputs under {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
