#!/usr/bin/env python3
"""Verify a configured MPH retail revision and prepare ndsrecomp inputs."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

try:
    import ndspy.codeCompression as code_compression
    import ndspy.rom
except ImportError as exc:
    raise SystemExit(
        "ndspy 4.2.0 is required; install requirements.txt into .venv"
    ) from exc


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROFILE_FILE = REPO_ROOT / "config" / "mph_rom_profiles.json"
DEFAULT_VERSION = "US1_0"


def sha1(data: bytes) -> str:
    return hashlib.sha1(data).hexdigest()


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def load_profile(path: Path, version: str) -> dict[str, object]:
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"unable to read ROM profile registry {path}: {exc}") from exc

    profiles = document.get("profiles")
    if not isinstance(profiles, dict):
        raise SystemExit(f"ROM profile registry has no object-valued 'profiles': {path}")
    profile = profiles.get(version)
    if not isinstance(profile, dict):
        choices = ", ".join(sorted(str(key) for key in profiles))
        raise SystemExit(
            f"unknown MPH version {version!r}; configured versions: {choices}"
        )

    required = {
        "display_name": str,
        "game_code": str,
        "revision": int,
        "rom_size": int,
        "sha1": str,
        "program_id": str,
    }
    for key, expected_type in required.items():
        value = profile.get(key)
        if not isinstance(value, expected_type):
            raise SystemExit(
                f"ROM profile {version!r} field {key!r} must be "
                f"{expected_type.__name__}"
            )

    game_code = str(profile["game_code"])
    if len(game_code) != 4 or not game_code.isascii():
        raise SystemExit(
            f"ROM profile {version!r} game_code must be exactly four ASCII bytes"
        )
    digest = str(profile["sha1"])
    if len(digest) != 40 or any(c not in "0123456789abcdef" for c in digest):
        raise SystemExit(
            f"ROM profile {version!r} sha1 must be 40 lowercase hex digits"
        )
    revision = int(profile["revision"])
    if revision < 0 or revision > 255:
        raise SystemExit(f"ROM profile {version!r} revision must fit one byte")
    rom_size = int(profile["rom_size"])
    if rom_size <= 0:
        raise SystemExit(f"ROM profile {version!r} rom_size must be positive")

    return profile


def write_seed_config(
    path: Path,
    *,
    name: str,
    program_id: str,
    load_address: int,
    entry_pc: int,
    binary: bytes,
    coverage_entries: list[dict[str, object]],
) -> None:
    lines = [
        "# AUTO-GENERATED by tools/prepare_mph.py; do not commit.",
        "[program]",
        f"name = {toml_string(name)}",
        f"id = {toml_string(program_id)}",
        f"load_address = 0x{load_address:08x}",
        f"size = 0x{len(binary):08x}",
        f"entry_pc = 0x{entry_pc:08x}",
        "authoritative_entry_points = false",
        "",
        "[identity]",
        f"sha1 = {toml_string(sha1(binary))}",
        "",
        "[[entry_point]]",
        f"addr = 0x{entry_pc:08x}",
        'mode = "arm"',
        'name = "entry"',
        'kind = "rom_header"',
        "",
    ]
    for entry in coverage_entries:
        addr = int(str(entry["addr"]), 0)
        mode = str(entry["mode"])
        lines.extend(
            [
                "[[entry_point]]",
                f"addr = 0x{addr:08x}",
                f"mode = {toml_string(mode)}",
                f"name = {toml_string(f'coverage_{addr:08x}')}",
                'kind = "tier3_coverage"',
                "",
            ]
        )
    path.write_text(
        "\n".join(lines),
        encoding="utf-8",
        newline="\n",
    )


def write_overlay_config(
    path: Path,
    *,
    title: str,
    program_id: str,
    overlay_id: int,
    load_address: int,
    binary: bytes,
    bss_size: int,
    static_init_start: int,
    static_init_end: int,
) -> None:
    """Emit a recompiler seed config for one ARM9 overlay unit.

    An overlay has no ROM-header entry point: the guest's own loader copies
    the image to `load_address` and enters it through pointers the main image
    holds, so no root is seeded here. Real entry points arrive from Tier-3
    coverage recorded while this exact body was resident. The [overlay] table
    carries the facts a content-validated dispatch row needs: exact image
    identity and the static-init span, the one region the guest legitimately
    mutates after load.
    """
    lines = [
        "# AUTO-GENERATED by tools/prepare_mph.py; do not commit.",
        "[program]",
        f"name = {toml_string(f'{title} ARM9 overlay {overlay_id}')}",
        f"id = {toml_string(f'{program_id}_ov{overlay_id:03d}')}",
        f"load_address = 0x{load_address:08x}",
        f"size = 0x{len(binary):08x}",
        f"entry_pc = 0x{load_address:08x}",
        "authoritative_entry_points = false",
        "",
        "[identity]",
        f"sha1 = {toml_string(sha1(binary))}",
        "",
        "[overlay]",
        f"id = {overlay_id}",
        f"bss_size = 0x{bss_size:08x}",
        f"static_init_start = 0x{static_init_start:08x}",
        f"static_init_end = 0x{static_init_end:08x}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


# Overlays that load at or above this address target DSi-exclusive memory and
# are never mapped when the cartridge boots as a DS title.
DS_MAIN_RAM_LIMIT = 0x02400000


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument(
        "--coverage",
        type=Path,
        help=(
            "optional static coverage seed manifest; omit to bootstrap from "
            "the ROM-header ARM9/ARM7 entry points only"
        ),
    )
    parser.add_argument(
        "--version",
        default=DEFAULT_VERSION,
        help=f"ROM profile key (default: {DEFAULT_VERSION})",
    )
    parser.add_argument(
        "--profiles",
        type=Path,
        default=DEFAULT_PROFILE_FILE,
        help=f"ROM profile registry (default: {DEFAULT_PROFILE_FILE})",
    )
    args = parser.parse_args()

    profile = load_profile(args.profiles, args.version)
    expected_sha1 = str(profile["sha1"])
    expected_size = int(profile["rom_size"])
    expected_game_code = str(profile["game_code"]).encode("ascii")
    expected_revision = int(profile["revision"])
    display_name = str(profile["display_name"])
    program_id = str(profile["program_id"])

    rom_bytes = args.rom.read_bytes()
    digest = sha1(rom_bytes)
    if len(rom_bytes) != expected_size:
        raise SystemExit(
            f"ROM size mismatch for {args.version}: got {len(rom_bytes)}, "
            f"expected {expected_size}"
        )
    if digest != expected_sha1:
        raise SystemExit(
            f"ROM SHA-1 mismatch for {args.version}: got {digest}, "
            f"expected {expected_sha1}"
        )
    if rom_bytes[0x0C:0x10] != expected_game_code:
        raise SystemExit(
            f"game code mismatch for {args.version}: got "
            f"{rom_bytes[0x0C:0x10]!r}, expected {expected_game_code!r}"
        )
    if rom_bytes[0x1E] != expected_revision:
        raise SystemExit(
            f"ROM revision mismatch for {args.version}: got {rom_bytes[0x1E]}, "
            f"expected {expected_revision}"
        )

    rom = ndspy.rom.NintendoDSRom(rom_bytes)
    arm9_coverage: list[dict[str, object]] = []
    arm7_coverage: list[dict[str, object]] = []
    if args.coverage is not None:
        coverage = json.loads(args.coverage.read_text(encoding="utf-8"))
        if coverage.get("game_sha1") != expected_sha1:
            raise SystemExit(
                f"static coverage seed identity does not match {args.version}"
            )
        coverage_entries = coverage.get("entry_points", {})
        if not isinstance(coverage_entries, dict):
            raise SystemExit("coverage entry_points must be an object")
        arm9_coverage = list(coverage_entries.get("arm9", []))
        arm7_coverage = list(coverage_entries.get("arm7", []))

    arm9_compressed = bytes(rom.arm9)
    arm9 = code_compression.decompress(arm9_compressed)
    if len(arm9) < len(arm9_compressed):
        arm9 = arm9_compressed
    arm7 = bytes(rom.arm7)

    out = args.out.resolve()
    overlays_dir = out / "overlays"
    overlays_dir.mkdir(parents=True, exist_ok=True)
    (out / "arm9.bin").write_bytes(arm9)
    (out / "arm7.bin").write_bytes(arm7)

    write_seed_config(
        out / "arm9.toml",
        name=f"{display_name} ARM9 main",
        program_id=f"{program_id}_arm9",
        load_address=int(rom.arm9RamAddress),
        entry_pc=int(rom.arm9EntryAddress),
        binary=arm9,
        coverage_entries=arm9_coverage,
    )
    write_seed_config(
        out / "arm7.toml",
        name=f"{display_name} ARM7",
        program_id=f"{program_id}_arm7",
        load_address=int(rom.arm7RamAddress),
        entry_pc=int(rom.arm7EntryAddress),
        binary=arm7,
        coverage_entries=arm7_coverage,
    )

    overlay_manifest: list[dict[str, object]] = []
    for overlay_id, overlay in sorted(rom.loadArm9Overlays().items()):
        data = bytes(overlay.data)
        if len(data) != int(overlay.ramSize):
            raise SystemExit(
                f"overlay {overlay_id} length mismatch: "
                f"{len(data)} != {overlay.ramSize}"
            )
        filename = f"arm9_overlay_{overlay_id:03d}.bin"
        (overlays_dir / filename).write_bytes(data)
        if int(overlay.ramAddress) < DS_MAIN_RAM_LIMIT:
            write_overlay_config(
                overlays_dir / f"arm9_overlay_{overlay_id:03d}.toml",
                title=display_name,
                program_id=f"{program_id}_arm9",
                overlay_id=overlay_id,
                load_address=int(overlay.ramAddress),
                binary=data,
                bss_size=int(overlay.bssSize),
                static_init_start=int(overlay.staticInitStart),
                static_init_end=int(overlay.staticInitEnd),
            )
        else:
            print(
                f"overlay {overlay_id} at 0x{int(overlay.ramAddress):08x} "
                f"loads outside DS main RAM; no seed config emitted"
            )
        overlay_manifest.append(
            {
                "id": overlay_id,
                "file": filename,
                "file_id": int(overlay.fileID),
                "load_address": f"0x{int(overlay.ramAddress):08x}",
                "size": int(overlay.ramSize),
                "bss_size": int(overlay.bssSize),
                "static_init_start": f"0x{int(overlay.staticInitStart):08x}",
                "static_init_end": f"0x{int(overlay.staticInitEnd):08x}",
                "compressed_in_rom": bool(overlay.compressed),
                "compressed_size": int(overlay.compressedSize),
                "sha1": sha1(data),
            }
        )
    (out / "overlays.json").write_text(
        json.dumps(overlay_manifest, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    print(
        f"ROM verified: profile={args.version} code="
        f"{expected_game_code.decode('ascii')} revision={expected_revision} "
        f"SHA-1 {digest}"
    )
    if args.coverage is None:
        print("Static coverage: none; using ROM-header ARM9/ARM7 bootstrap roots only")
    else:
        print(
            f"Static coverage: {len(arm9_coverage)} ARM9 + "
            f"{len(arm7_coverage)} ARM7 seed entries from {args.coverage}"
        )
    print(
        f"ARM9: {len(arm9_compressed):,} compressed bytes -> "
        f"{len(arm9):,} bytes at 0x{int(rom.arm9RamAddress):08X}"
    )
    print(
        f"ARM7: {len(arm7):,} bytes at "
        f"0x{int(rom.arm7RamAddress):08X}"
    )
    print(f"ARM9 overlays: {len(overlay_manifest)} extracted and inventoried")
    print(f"Prepared ignored inputs under {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
