#!/usr/bin/env python3
"""Verify AMHE0 and prepare ignored ndsrecomp main/overlay inputs."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

try:
    import ndspy.codeCompression as code_compression
    import ndspy.rom
except ImportError as exc:
    raise SystemExit(
        "ndspy 4.2.0 is required; install requirements.txt into .venv"
    ) from exc


EXPECTED_ROM_SHA1 = "90164d1ac127ee5f9815ea4ae7de798c7b5fc629"
EXPECTED_ROM_SIZE = 64 * 1024 * 1024
EXPECTED_GAME_CODE = b"AMHE"
EXPECTED_REVISION = 0


def sha1(data: bytes) -> str:
    return hashlib.sha1(data).hexdigest()


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def write_seed_config(
    path: Path,
    *,
    name: str,
    program_id: str,
    load_address: int,
    entry_pc: int,
    binary: bytes,
    coverage_entries: list[dict[str, object]],
) -> None:
    lines = [
                "# AUTO-GENERATED by tools/prepare_mph.py; do not commit.",
                "[program]",
                f"name = {toml_string(name)}",
                f"id = {toml_string(program_id)}",
                f"load_address = 0x{load_address:08x}",
                f"size = 0x{len(binary):08x}",
                f"entry_pc = 0x{entry_pc:08x}",
                "authoritative_entry_points = false",
                "",
                "[identity]",
                f"sha1 = {toml_string(sha1(binary))}",
                "",
                "[[entry_point]]",
                f"addr = 0x{entry_pc:08x}",
                'mode = "arm"',
                'name = "entry"',
                'kind = "rom_header"',
                "",
            ]
    for entry in coverage_entries:
        addr = int(str(entry["addr"]), 0)
        mode = str(entry["mode"])
        lines.extend(
            [
                "[[entry_point]]",
                f"addr = 0x{addr:08x}",
                f"mode = {toml_string(mode)}",
                f"name = {toml_string(f'coverage_{addr:08x}')}",
                'kind = "tier3_coverage"',
                "",
            ]
        )
    path.write_text(
        "\n".join(lines),
        encoding="utf-8",
        newline="\n",
    )


def write_alias_config(
    path: Path,
    *,
    name: str,
    program_id: str,
    load_address: int,
    binary: bytes,
    coverage_entries: list[dict[str, object]],
) -> None:
    """Emit a seed config recompiling an already-declared module at an alias base.

    MPH's ARM7 module is declared once at its ROM-header base (0x02380000) but
    the guest relocates and runs it from other bases -- 0x037F7E50 (the ARM7
    WRAM window) and 0x027CFBC4 (a main-RAM window). Code reached at those
    addresses matched no bank, so it fell to the Tier-3 interpreter forever
    (beads-lqa.9). The fix needs no dumped bytes: recompile the SAME arm7.bin
    at each resident base and let --validate-live-bytes gate every function
    against the live guest image before dispatch.

    There is no ROM-header entry point at an alias base, so no synthetic root
    is seeded: every entry point comes from Tier-3 coverage recorded while the
    module was resident at this exact base, and entry_pc is the lowest such
    seed (mirroring mph_arm7_mp_wram_runtime, whose entry_pc is likewise its
    lowest observed entry rather than a header value).
    """
    if not coverage_entries:
        raise SystemExit(f"{program_id}: alias banks require coverage seeds")
    addrs = sorted(int(str(entry["addr"]), 0) for entry in coverage_entries)
    entry_pc = addrs[0]
    limit = load_address + len(binary)
    if not load_address <= entry_pc < limit:
        raise SystemExit(
            f"{program_id}: entry_pc 0x{entry_pc:08x} outside the image "
            f"[0x{load_address:08x}, 0x{limit:08x})"
        )
    lines = [
        "# AUTO-GENERATED by tools/prepare_mph.py; do not commit.",
        "[program]",
        f"name = {toml_string(name)}",
        f"id = {toml_string(program_id)}",
        'cpu = "arm7"',
        'isa = "armv4t"',
        f"load_address = 0x{load_address:08x}",
        f"size = 0x{len(binary):08x}",
        f"entry_pc = 0x{entry_pc:08x}",
        "authoritative_entry_points = false",
        "",
        "[identity]",
        f"sha1 = {toml_string(sha1(binary))}",
        "",
    ]
    for addr in addrs:
        entry = next(
            e for e in coverage_entries if int(str(e["addr"]), 0) == addr
        )
        lines.extend(
            [
                "[[entry_point]]",
                f"addr = 0x{addr:08x}",
                f"mode = {toml_string(str(entry['mode']))}",
                f"name = {toml_string(f'alias_{addr:08x}')}",
                'kind = "runtime_observed"',
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def write_overlay_config(
    path: Path,
    *,
    title: str,
    program_id: str,
    overlay_id: int,
    load_address: int,
    binary: bytes,
    bss_size: int,
    static_init_start: int,
    static_init_end: int,
) -> None:
    """Emit a recompiler seed config for one ARM9 overlay unit.

    An overlay has no ROM-header entry point: the guest's own loader copies
    the image to `load_address` and enters it through pointers the main image
    holds, so no root is seeded here — real entry points arrive from Tier-3
    coverage recorded while this exact body was resident (the
    PokemonBlackWhiteRecomp probe/build tools are the reference consumers).
    The [overlay] table carries the facts a content-validated dispatch row
    needs: the exact image identity and the static-init span, the one region
    the guest legitimately mutates after load.
    """
    lines = [
        "# AUTO-GENERATED by tools/prepare_mph.py; do not commit.",
        "[program]",
        f"name = {toml_string(f'{title} ARM9 overlay {overlay_id}')}",
        f"id = {toml_string(f'{program_id}_ov{overlay_id:03d}')}",
        f"load_address = 0x{load_address:08x}",
        f"size = 0x{len(binary):08x}",
        f"entry_pc = 0x{load_address:08x}",
        "authoritative_entry_points = false",
        "",
        "[identity]",
        f"sha1 = {toml_string(sha1(binary))}",
        "",
        "[overlay]",
        f"id = {overlay_id}",
        f"bss_size = 0x{bss_size:08x}",
        f"static_init_start = 0x{static_init_start:08x}",
        f"static_init_end = 0x{static_init_end:08x}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


# Overlays that load at or above this address target DSi-exclusive memory and
# are never mapped when the cartridge boots as a DS title.
DS_MAIN_RAM_LIMIT = 0x02400000

# ARM7 alias banks (beads-lqa.9): the ROM's arm7.bin recompiled a second and
# third time at the bases the guest actually relocates it to. Each entry is
# (coverage key, config filename, program id, resident load address, name).
ARM7_ALIAS_BANKS = (
    (
        "arm7_wram_alias",
        "arm7_wram_alias.toml",
        "mph_amhe0_arm7_wram_alias",
        0x037F7E50,
        "Metroid Prime Hunters (USA rev 0) ARM7 @ WRAM alias base",
    ),
    (
        "arm7_mainram_alias",
        "arm7_mainram_alias.toml",
        "mph_amhe0_arm7_mainram_alias",
        0x027CFBC4,
        "Metroid Prime Hunters (USA rev 0) ARM7 @ main-RAM alias base",
    ),
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--coverage", type=Path, required=True)
    parser.add_argument(
        "--arm7-alias-coverage",
        type=Path,
        required=True,
        help="coverage/arm7-alias-entry-points.json: the Tier-3 entry points "
        "observed while arm7.bin was resident at its relocated bases",
    )
    args = parser.parse_args()

    rom_bytes = args.rom.read_bytes()
    digest = sha1(rom_bytes)
    if len(rom_bytes) != EXPECTED_ROM_SIZE:
        raise SystemExit(
            f"ROM size mismatch: got {len(rom_bytes)}, expected {EXPECTED_ROM_SIZE}"
        )
    if digest != EXPECTED_ROM_SHA1:
        raise SystemExit(
            f"ROM SHA-1 mismatch: got {digest}, expected {EXPECTED_ROM_SHA1}"
        )
    if rom_bytes[0x0C:0x10] != EXPECTED_GAME_CODE:
        raise SystemExit(
            f"game code mismatch: got {rom_bytes[0x0C:0x10]!r}, "
            f"expected {EXPECTED_GAME_CODE!r}"
        )
    if rom_bytes[0x1C] != EXPECTED_REVISION:
        raise SystemExit(
            f"ROM revision mismatch: got {rom_bytes[0x1C]}, "
            f"expected {EXPECTED_REVISION}"
        )

    rom = ndspy.rom.NintendoDSRom(rom_bytes)
    coverage = json.loads(args.coverage.read_text(encoding="utf-8"))
    if coverage.get("game_sha1") != EXPECTED_ROM_SHA1:
        raise SystemExit("static coverage seed identity does not match AMHE0")
    coverage_entries = coverage.get("entry_points", {})
    arm9_coverage = list(coverage_entries.get("arm9", []))
    arm7_coverage = list(coverage_entries.get("arm7", []))
    alias_coverage = json.loads(
        args.arm7_alias_coverage.read_text(encoding="utf-8")
    )
    if alias_coverage.get("game_sha1") != EXPECTED_ROM_SHA1:
        raise SystemExit("ARM7 alias coverage seed identity does not match AMHE0")
    alias_entries = alias_coverage.get("entry_points", {})
    arm9_compressed = bytes(rom.arm9)
    arm9 = code_compression.decompress(arm9_compressed)
    if len(arm9) < len(arm9_compressed):
        arm9 = arm9_compressed
    arm7 = bytes(rom.arm7)

    out = args.out.resolve()
    overlays_dir = out / "overlays"
    overlays_dir.mkdir(parents=True, exist_ok=True)
    (out / "arm9.bin").write_bytes(arm9)
    (out / "arm7.bin").write_bytes(arm7)

    write_seed_config(
        out / "arm9.toml",
        name="Metroid Prime Hunters (USA rev 0) ARM9 main",
        program_id="mph_amhe0_arm9",
        load_address=int(rom.arm9RamAddress),
        entry_pc=int(rom.arm9EntryAddress),
        binary=arm9,
        coverage_entries=arm9_coverage,
    )
    write_seed_config(
        out / "arm7.toml",
        name="Metroid Prime Hunters (USA rev 0) ARM7",
        program_id="mph_amhe0_arm7",
        load_address=int(rom.arm7RamAddress),
        entry_pc=int(rom.arm7EntryAddress),
        binary=arm7,
        coverage_entries=arm7_coverage,
    )

    alias_summaries: list[str] = []
    for key, filename, program_id, load_address, name in ARM7_ALIAS_BANKS:
        seeds = list(alias_entries.get(key, []))
        if not seeds:
            raise SystemExit(
                f"ARM7 alias coverage has no entry points for '{key}'"
            )
        write_alias_config(
            out / filename,
            name=name,
            program_id=program_id,
            load_address=load_address,
            binary=arm7,
            coverage_entries=seeds,
        )
        alias_summaries.append(
            f"ARM7 alias bank {program_id}: {len(seeds):,} seeds at "
            f"0x{load_address:08X}"
        )

    overlay_manifest: list[dict[str, object]] = []
    for overlay_id, overlay in sorted(rom.loadArm9Overlays().items()):
        data = bytes(overlay.data)
        if len(data) != int(overlay.ramSize):
            raise SystemExit(
                f"overlay {overlay_id} length mismatch: "
                f"{len(data)} != {overlay.ramSize}"
            )
        filename = f"arm9_overlay_{overlay_id:03d}.bin"
        (overlays_dir / filename).write_bytes(data)
        if int(overlay.ramAddress) < DS_MAIN_RAM_LIMIT:
            write_overlay_config(
                overlays_dir / f"arm9_overlay_{overlay_id:03d}.toml",
                title="Metroid Prime Hunters (USA rev 0)",
                program_id="mph_amhe0_arm9",
                overlay_id=overlay_id,
                load_address=int(overlay.ramAddress),
                binary=data,
                bss_size=int(overlay.bssSize),
                static_init_start=int(overlay.staticInitStart),
                static_init_end=int(overlay.staticInitEnd),
            )
        else:
            print(
                f"overlay {overlay_id} at 0x{int(overlay.ramAddress):08x} "
                f"loads outside DS main RAM; no seed config emitted"
            )
        overlay_manifest.append(
            {
                "id": overlay_id,
                "file": filename,
                "file_id": int(overlay.fileID),
                "load_address": f"0x{int(overlay.ramAddress):08x}",
                "size": int(overlay.ramSize),
                "bss_size": int(overlay.bssSize),
                "static_init_start": f"0x{int(overlay.staticInitStart):08x}",
                "static_init_end": f"0x{int(overlay.staticInitEnd):08x}",
                "compressed_in_rom": bool(overlay.compressed),
                "compressed_size": int(overlay.compressedSize),
                "sha1": sha1(data),
            }
        )
    (out / "overlays.json").write_text(
        json.dumps(overlay_manifest, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"ROM verified: AMHE revision 0, SHA-1 {digest}")
    print(
        f"ARM9: {len(arm9_compressed):,} compressed bytes -> "
        f"{len(arm9):,} bytes at 0x{int(rom.arm9RamAddress):08X}"
    )
    print(
        f"ARM7: {len(arm7):,} bytes at "
        f"0x{int(rom.arm7RamAddress):08X}"
    )
    for summary in alias_summaries:
        print(summary)
    print(f"ARM9 overlays: {len(overlay_manifest)} extracted and inventoried")
    print(f"Prepared ignored inputs under {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
