#!/usr/bin/env python3
"""Create a content-validated runtime-bank config from live captures.

Generalizes tools/promote_mph_runtime_coverage.py (ARM9 FMV window only) to
any CPU and any capture window, and accepts several benchmark/before pairs
(e.g. the host and the guest of a local-wireless session) whose coverage
deltas are unioned. Benchmarks are JSON of the shape
{"tier3_coverage": {"entries": [...]}} — either a runner benchmark report
or a saved debug-server `tier3_coverage` response wrapped in that key.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def parse_int(text: str) -> int:
    return int(text, 0)


def load_entries(path: Path) -> list[dict[str, object]]:
    report = json.loads(path.read_text(encoding="utf-8"))
    return report.get("tier3_coverage", {}).get("entries", [])


def coverage_key(item: dict[str, object]) -> tuple[int, ...]:
    return tuple(
        int(item[field]) for field in ("cpu", "pc", "thumb", "kind", "caller")
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--benchmark", type=Path, action="append", required=True,
        help="coverage report captured during the target phase (repeatable)",
    )
    parser.add_argument(
        "--before-benchmark", type=Path, action="append", default=[],
        help="cumulative coverage captured before the target phase; "
        "paired positionally with --benchmark",
    )
    parser.add_argument("--image", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--bank", required=True)
    parser.add_argument("--name", required=True,
                        help='[program] name, e.g. "MPH ARM7 MP WRAM runtime"')
    parser.add_argument("--cpu", type=int, choices=(7, 9), required=True)
    parser.add_argument("--load-address", type=parse_int, required=True)
    parser.add_argument("--size", type=parse_int, required=True)
    parser.add_argument(
        "--include-slice-resumes", action="store_true",
        help="also seed kind-1 scheduler resume PCs (usually fragments code)",
    )
    args = parser.parse_args()

    if args.before_benchmark and \
            len(args.before_benchmark) != len(args.benchmark):
        raise SystemExit(
            "--before-benchmark must be given once per --benchmark")

    image = args.image.read_bytes()
    if len(image) != args.size:
        raise SystemExit(
            f"runtime image is 0x{len(image):X} bytes; "
            f"expected 0x{args.size:X}")
    identity = hashlib.sha1(image).hexdigest()

    coverage: list[dict[str, object]] = []
    for i, bench in enumerate(args.benchmark):
        entries = load_entries(bench)
        if args.before_benchmark:
            before_hits = {
                coverage_key(item): int(item["hits"])
                for item in load_entries(args.before_benchmark[i])
            }
            entries = [
                item for item in entries
                if int(item["hits"]) -
                before_hits.get(coverage_key(item), 0) > 0
            ]
        coverage.extend(entries)

    lo = args.load_address
    hi = args.load_address + args.size
    entry_points = sorted({
        (int(item["pc"]), "thumb" if int(item["thumb"]) else "arm")
        for item in coverage
        if int(item["cpu"]) == args.cpu
        and lo <= int(item["pc"]) < hi
        and (args.include_slice_resumes or int(item["kind"]) in (2, 3))
    })
    if not entry_points:
        raise SystemExit(
            "benchmarks contain no matching runtime Tier-3 coverage")

    lines = [
        "# AUTO-GENERATED by tools/promote_runtime_coverage.py; committed.",
        f"# Source is generated/capture/{args.bank}.bin (git-ignored).",
        "# Every function is validated against live guest bytes before"
        " dispatch.",
        "",
        "[program]",
        f'name         = "{args.name}"',
        f'id           = "{args.bank}"',
        f'cpu          = "arm{args.cpu}"',
        f'isa          = "{"armv5te" if args.cpu == 9 else "armv4t"}"',
        f"load_address = 0x{args.load_address:08X}",
        f"size         = 0x{args.size:08X}",
        f"entry_pc     = 0x{entry_points[0][0]:08X}",
        "",
        "[identity]",
        f'sha1 = "{identity}"',
        "",
    ]
    for address, mode in entry_points:
        lines += [
            "[[entry_point]]",
            f"addr = 0x{address:08X}",
            f'mode = "{mode}"',
            'kind = "runtime_observed"',
            "",
        ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(json.dumps({
        "config": str(args.out),
        "image_sha1": identity,
        "entry_points": len(entry_points),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
