#!/usr/bin/env python3
"""Create a content-validated MPH ARM9 runtime-bank config from a capture."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ITCM_BASE = 0x01FF8000
MAIN_RAM_END = 0x02400000
IMAGE_SIZE = 0x00408000


def runtime_address(address: int) -> bool:
    return ITCM_BASE <= address < MAIN_RAM_END


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--benchmark", type=Path, required=True)
    parser.add_argument(
        "--before-benchmark", type=Path,
        help="subtract cumulative coverage captured before the target phase",
    )
    parser.add_argument("--image", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--bank", default="mph_arm9_fmv_runtime")
    parser.add_argument(
        "--include-slice-resumes", action="store_true",
        help="also seed kind-1 scheduler resume PCs (usually fragments code)",
    )
    args = parser.parse_args()

    image = args.image.read_bytes()
    if len(image) != IMAGE_SIZE:
        raise SystemExit(
            f"runtime image is 0x{len(image):X} bytes; expected 0x{IMAGE_SIZE:X}"
        )
    identity = hashlib.sha1(image).hexdigest()
    report = json.loads(args.benchmark.read_text(encoding="utf-8"))
    coverage = report.get("tier3_coverage", {}).get("entries", [])
    if args.before_benchmark is not None:
        before_report = json.loads(
            args.before_benchmark.read_text(encoding="utf-8")
        )
        before_entries = before_report.get(
            "tier3_coverage", {}
        ).get("entries", [])

        def coverage_key(item: dict[str, object]) -> tuple[int, ...]:
            return tuple(
                int(item[field])
                for field in ("cpu", "pc", "thumb", "kind", "caller")
            )

        before_hits = {
            coverage_key(item): int(item["hits"])
            for item in before_entries
        }
        coverage = [
            item for item in coverage
            if int(item["hits"]) - before_hits.get(coverage_key(item), 0) > 0
        ]
    entries = sorted({
        (int(item["pc"]), "thumb" if int(item["thumb"]) else "arm")
        for item in coverage
        if int(item["cpu"]) == 9
        and runtime_address(int(item["pc"]))
        and (args.include_slice_resumes or int(item["kind"]) in (2, 3))
    })
    if not entries:
        raise SystemExit("benchmark contains no ARM9 runtime Tier-3 coverage")

    lines = [
        "# AUTO-GENERATED by tools/promote_mph_runtime_coverage.py; committed.",
        "# Source is generated/capture/mph_arm9_fmv_runtime.bin (git-ignored).",
        "# Every function is validated against live guest bytes before dispatch.",
        "",
        "[program]",
        'name         = "Metroid Prime Hunters (USA) ARM9 FMV runtime"',
        f'id           = "{args.bank}"',
        'cpu          = "arm9"',
        'isa          = "armv5te"',
        f"load_address = 0x{ITCM_BASE:08X}",
        f"size         = 0x{IMAGE_SIZE:08X}",
        f"entry_pc     = 0x{entries[0][0]:08X}",
        "",
        "[identity]",
        f'sha1 = "{identity}"',
        "",
    ]
    for address, mode in entries:
        lines += [
            "[[entry_point]]",
            f"addr = 0x{address:08X}",
            f'mode = "{mode}"',
            'kind = "runtime_observed"',
            "",
        ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(json.dumps({
        "config": str(args.out),
        "image_sha1": identity,
        "entry_points": len(entries),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
